### ISSUE TITLE
Code errors after submitting application

### ISSUE THREAD

**Issue by RedRiverDelta** [coding-ai/EasyApply-Linkedin#1]
The code works fine up until submitting an application. After that, it goes to a confirmation screen and doesn't exit out of that.

**Comment by AhmedCheikh** [comment]
Hello, 
Everything works fine until this popup comes out 
![Capture](https://user-images.githubusercontent.com/33034470/72947743-50925980-3d83-11ea-9fde-c50c430237be.PNG)

**Comment by solcyborg** [comment]
See @coding-ai other comments from another user... it seems you may need premium or adjust the coding. Maybe you can Xpath the X with a wait time and click() with selenium.

**Comment by coding-ai** [comment]
LinkedIn is constantly changing their website to avoid bots. This issue is totally normal. Due to this, I am not maintaining the code - I decided to make a YouTube video to explain how to build this program https://www.youtube.com/watch?v=6plKL95a134
You can watch how I get the different elements in this video and you just need to change a couple of lines of code, depending on the current elements that LinkedIn has on the website. 
Thanks!
