### ISSUE TITLE
Perhaps the design of this page has changed

### ISSUE THREAD

**Issue by alexqueroz** [coding-ai/EasyApply-Linkedin#6]
The design of the page may have changed because it doesn't work anymore. It stops right after login at the job page.

**Comment by solcyborg** [comment]
Check some of the recent contributions. It needs to have a wait time for the page to load for it to run properly. @An-dang made it work. 

Although, I think some elements have changed when it comes to applying filters. Mine is getting hung up on the easy apply button to filter.

**Comment by lavellshit** [comment]
I am so confused.

**Comment by applicatlat** [comment]
I tried to change the code with the new design but it gave me this error:    

 raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-search-box__text-input[aria-label='Search by title, skill, or company']"}
  (Session info: chrome=89.0.4389.90)

**Comment by jldmorris** [comment]
Same here :(

**Comment by coding-ai** [comment]
LinkedIn is constantly changing their website to avoid bots. This issue is totally normal. Due to this, I am not maintaining the code - I decided to make a YouTube video to explain how to build this program https://www.youtube.com/watch?v=6plKL95a134
You can watch how I get the different elements in this video and you just need to change a couple of lines of code, depending on the current elements that LinkedIn has on the website. 
Thanks!
