### ISSUE TITLE
Not working fine

### ISSUE THREAD

**Issue by kalashjindal** [coding-ai/EasyApply-Linkedin#7]
I am trying to run it  but I got the error
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-search-box__text-input[aria-label='Search jobs']"}
  (Session info: chrome=92.0.4515.159)

**Comment by coding-ai** [comment]
LinkedIn is constantly changing their website to avoid bots. This issue is totally normal. Due to this, I am not maintaining the code - I decided to make a YouTube video to explain how to build this program https://www.youtube.com/watch?v=6plKL95a134
You can watch how I get the different elements in this video and you just need to change a couple of lines of code, depending on the current elements that LinkedIn has on the website. 
Thanks!
